spring:
  h2:
    console:
      enabled: true
  #      settings:
  #        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/quicktrip
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # create: ???? ??? ??(?????? ?? ??? ?? ???? ?? ???? ?? ??), none: ?? ???? ???? ??
    properties:
      hibernate:
        #        show_sql: true  # sout? ?? ?? sql ?? ??
        format_sql: true

  data:
    rest:
      # API? ?? ??? ?? ??? ???
      base-path: /api
      # ?????? ?? ??? ??? ???? ??? ? ?? ? ?? ??? ??? ??
      default-page-size: 10
      # ?? ??? ?? ??
      max-page-size: 10

logging:
  level:
    org.hibernate.sql: debug  # logger? ?? ?? sql ?? ??
    org.hibernate.type: trace